Repository HRHN-HaruHana/HRHN-iOS, pull requests merged in 2022-12, with the labels that each got.

#14 [Feat] 프로젝트 기본설정
  HRHN.xcodeproj/project.pbxproj
  HRHN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HRHN.xcodeproj/xcuserdata/chanheejeong.xcuserdatad/xcschemes/xcschememanagement.plist
  HRHN/Base.lproj/Main.storyboard
  HRHN/Extension/SampleExtension.swift
  HRHN/Info.plist
  HRHN/Model/CoreData/CoreDataManager.swift
  HRHN/Model/CoreData/HRHN.xcdatamodeld/.xccurrentversion
  HRHN/Model/CoreData/HRHN.xcdatamodeld/HRHN.xcdatamodel/contents
  HRHN/Model/Repository/SampleRepository.swift
  HRHN/Model/SampleModel.swift
  HRHN/SceneDelegate.swift
  HRHN/View/UI/SampleUI.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewController.swift
  HRHN/ViewModel/SampleViewModel.swift
Labels: 세팅

#18 [Feat] 기기별 오토레이아웃 대응
  .gitignore
  HRHN.xcodeproj/project.pbxproj
  HRHN.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  HRHN.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  HRHN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HRHN/Extension/CGFloat+.swift
  HRHN/Extension/Double+.swift
  HRHN/Managers/DeviceManager.swift
Labels: enhancement, design

#21 [Feat] 기기별 오토레이아웃 대응 (iOS16)
  HRHN/Managers/DeviceManager.swift
Labels: enhancement, design

#22 [Setting/Feat] 코어데이터설정, 코어데이터매니저 및 데이터모델
  HRHN.xcodeproj/project.pbxproj
  HRHN/AppDelegate.swift
  HRHN/Managers/CoreDataManager.swift
  HRHN/Model/Challenge.swift
  HRHN/Model/CoreData/ChallengeMO+CoreDataClass.swift
  HRHN/Model/CoreData/ChallengeMO+CoreDataProperties.swift
  HRHN/Model/CoreData/CoreDataManager.swift
  HRHN/Model/CoreData/HRHN.xcdatamodeld/HRHN.xcdatamodel/contents
  HRHN/Model/Repository/SampleRepository.swift
  HRHN/Model/SampleModel.swift
  HRHN/SceneDelegate.swift
  HRHN/View/VC/RecordViewController.swift
  HRHN/View/VC/TodayViewController.swift
Labels: 세팅, 기능추가

#23 [Feat] 오늘의 챌린지 UI
  HRHN.xcodeproj/project.pbxproj
  HRHN/Extension/Date+.swift
  HRHN/SampleViewModel.swift
  HRHN/View/VC/TabBarController.swift
  HRHN/View/VC/TodayViewController.swift
Labels: UI

#26 [Feat] 지난챌린지 UI
  HRHN.xcodeproj/project.pbxproj
  HRHN/Assets.xcassets/blue.imageset/Contents.json
  HRHN/Assets.xcassets/blue.imageset/blue.svg
  HRHN/Assets.xcassets/green.imageset/Contents.json
  HRHN/Assets.xcassets/green.imageset/green.svg
  HRHN/Assets.xcassets/purple.imageset/Contents.json
  HRHN/Assets.xcassets/purple.imageset/purple.svg
  HRHN/Assets.xcassets/red.imageset/Contents.json
  HRHN/Assets.xcassets/red.imageset/red.svg
  HRHN/Assets.xcassets/skyblue.imageset/Contents.json
  HRHN/Assets.xcassets/skyblue.imageset/skyblue.svg
  HRHN/Assets.xcassets/yellow.imageset/Contents.json
  HRHN/Assets.xcassets/yellow.imageset/yellow.svg
  HRHN/Color/CustomColor.swift
  HRHN/Color/UIColor+.swift
  HRHN/Model/Challenge.swift
  HRHN/Model/MockData.swift
  HRHN/SampleViewModel.swift
  HRHN/View/UI/Cell/ChallengeCell.swift
  HRHN/View/UI/Cell/ChallengeCellView.swift
  HRHN/View/UI/Cell/RecordHeaderView.swift
  HRHN/View/VC/RecordViewController.swift
  HRHN/View/VC/TabBarController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/RecordViewModel.swift
Labels: 기능추가, UI

#30 [Feat] 오늘의 챌린지 데이터 작업
  HRHN.xcodeproj/project.pbxproj
  HRHN/Helper/Obervable.swift
  HRHN/View/VC/TabBarController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/TodayViewModel.swift
Labels: 기능추가

#31 [Feat] 지난챌린지 데이터 작업
  HRHN.xcodeproj/project.pbxproj
  HRHN/View/VC/RecordViewController.swift
  HRHN/ViewModel/RecordViewModel.swift
Labels: 기능추가

#32 [Feat] FullWidthButton 컴포넌트 제작
  HRHN.xcodeproj/project.pbxproj
  HRHN/View/UI/Component/FullWidthButton.swift
  HRHN/View/UI/Component/UIFullWidthButton.swift
Labels: SwiftUI, UI

#35 [DesignSystem] SwiftUI Color
  HRHN.xcodeproj/project.pbxproj
  HRHN/Color/Color+.swift
  HRHN/Color/UIColor+.swift
  HRHN/View/UI/Cell/ChallengeCellView.swift
Labels: 세팅, SwiftUI, design

#36 [Feat] 챌린지 평가 UI
  HRHN.xcodeproj/project.pbxproj
  HRHN.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HRHN/Extension/UIViewController+.swift
  HRHN/Extension/View+.swift
  HRHN/View/UI/SampleUI.swift
  HRHN/View/UI/SwiftUIView/ReviewView.swift
  HRHN/View/VC/ReviewViewController.swift
Labels: SwiftUI, UI

#38 [Feat] 챌린지 평가 로직
  .gitignore
  HRHN.xcodeproj/project.pbxproj
  HRHN/View/UI/SwiftUIView/ReviewView.swift
  HRHN/View/VC/ReviewViewController.swift
  HRHN/ViewModel/ReviewViewModel.swift
Labels: 기능추가

#41 [Feat] 챌린지 등록 UI
  HRHN.xcodeproj/project.pbxproj
  HRHN/Extension/UITextView+.swift
  HRHN/View/VC/AddViewController.swift
  HRHN/View/VC/ReviewViewController.swift
Labels: UI

#40 [Feat] 설정 UI
  HRHN.xcodeproj/project.pbxproj
  HRHN/View/UI/Cell/SettingCell.swift
  HRHN/View/VC/RecordViewController.swift
  HRHN/View/VC/SettingViewController.swift
  HRHN/View/VC/TodayViewController.swift
Labels: 기능추가, UI

#43 [Feat] 챌린지 등록 로직
  HRHN.xcodeproj/project.pbxproj
  HRHN/View/VC/AddViewController.swift
  HRHN/View/VC/ReviewViewController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/AddViewModel.swift
  HRHN/ViewModel/TodayViewModel.swift
Labels: 기능추가

#46 [HOTFIX] pbxproj 오류
  .gitignore
  HRHN.xcodeproj/project.pbxproj
Labels: bug

#44 [Feat] 알림추가 (설정페이지)
  HRHN.xcodeproj/project.pbxproj
  HRHN/AppDelegate.swift
  HRHN/Extension/UserDefaults+.swift
  HRHN/View/UI/Cell/SettingCell.swift
  HRHN/View/VC/RecordViewController.swift
  HRHN/View/VC/SettingViewController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/SettingViewModel.swift
  HRHN/ViewModel/TodayViewModel.swift
Labels: 기능추가

#49 [Bug] 아무것도 작성하지 않은 챌린지를 추가할 수 있는 버그
  HRHN/View/VC/AddViewController.swift
Labels: bug

#48 [Feat] 락스크린 위젯
  HRHN.xcodeproj/project.pbxproj
  HRHN/AppDelegate.swift
  HRHN/Extension/URL+.swift
  HRHN/HRHN.entitlements
  HRHN/Managers/CoreDataManager.swift
  HRHN/SceneDelegate.swift
  HRHN/View/VC/AddViewController.swift
  HRHN/ViewModel/AddViewModel.swift
  LockscreenWidget/Assets.xcassets/AccentColor.colorset/Contents.json
  LockscreenWidget/Assets.xcassets/AppIcon.appiconset/Contents.json
  LockscreenWidget/Assets.xcassets/Contents.json
  LockscreenWidget/Assets.xcassets/WidgetBackground.colorset/Contents.json
  LockscreenWidget/Info.plist
  LockscreenWidget/LockscreenWidget.intentdefinition
  LockscreenWidget/LockscreenWidget.swift
  LockscreenWidgetExtension.entitlements
Labels: 기능추가, SwiftUI

#51 [Feat] 온보딩
  HRHN.xcodeproj/project.pbxproj
  HRHN/AppDelegate.swift
  HRHN/Assets.xcassets/emoji/Contents.json
  HRHN/Assets.xcassets/emoji/blue.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/blue.imageset/blue.svg
  HRHN/Assets.xcassets/emoji/green.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/green.imageset/green.svg
  HRHN/Assets.xcassets/emoji/purple.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/purple.imageset/purple.svg
  HRHN/Assets.xcassets/emoji/red.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/red.imageset/red.svg
  HRHN/Assets.xcassets/emoji/skyblue.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/skyblue.imageset/skyblue.svg
  HRHN/Assets.xcassets/emoji/yellow.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/yellow.imageset/yellow.svg
  HRHN/Assets.xcassets/onboarding/Contents.json
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/Contents.json
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/onboarding-1.svg
  HRHN/Extension/UserDefaults+.swift
  HRHN/SceneDelegate.swift
  HRHN/View/VC/OnBoarding/OBFirstViewController.swift
  HRHN/View/VC/OnBoarding/OBSecondViewController.swift
  HRHN/View/VC/OnBoarding/OBThirdViewController.swift
  HRHN/View/VC/OnBoarding/OnBoardingPageViewController.swift
  HRHN/ViewModel/OnBoardingViewModel.swift
Labels: 기능추가

#53 [Bug] 글자수 제한 추가
  HRHN/View/VC/AddViewController.swift
Labels: bug

#54 [Feat] Asset 추가
  HRHN/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  HRHN/Assets.xcassets/AppIcon.appiconset/Contents.json
  HRHN/Assets.xcassets/emoji/none.imageset/Contents.json
  HRHN/Assets.xcassets/emoji/none.imageset/none.svg
  HRHN/Assets.xcassets/onboarding/mock.imageset/Contents.json
  HRHN/Assets.xcassets/onboarding/mock.imageset/mock.png
  HRHN/View/VC/OnBoarding/OBSecondViewController.swift
  HRHN/View/VC/OnBoarding/OnBoardingPageViewController.swift
Labels: design

#59 [Setting] 배포설정
  HRHN.xcodeproj/project.pbxproj
  HRHN/HRHN.entitlements
  HRHN/Info.plist
  HRHN/Managers/CoreDataManager.swift
  LockscreenWidgetExtension.entitlements
Labels: 세팅

#64 [Bug] 챌린지 타임존 버그
  HRHN.xcodeproj/project.pbxproj
  HRHN/AppDelegate.swift
  HRHN/Extension/Date+.swift
  HRHN/Extension/DateComponents+.swift
  HRHN/Managers/CoreDataManager.swift
  HRHN/View/VC/TodayViewController.swift
  LockscreenWidget/LockscreenWidget.swift
Labels: bug
