Repository HRHN-HaruHana/HRHN-iOS, pull requests merged in 2023-01, with the labels that each got.

#66 [HOTFIX] ITMS-90626: Invalid Siri Support 리젝 사유 수정
  HRHN.xcodeproj/project.pbxproj
  LockscreenWidget/LockscreenWidget.intentdefinition
  LockscreenWidget/LockscreenWidget.swift
Labels: invalid

#68 [Hotfix] 앱스토어 수출문서 누락 관련 info.plist 설정
  HRHN/Info.plist
Labels: 세팅

#71 [UI] Dark Mode
  HRHN.xcodeproj/project.pbxproj
  HRHN/Assets.xcassets/AccentColor.colorset/Contents.json
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/Contents.json
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/dark.svg
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/light.svg
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/onboarding-1.svg
  HRHN/Color/Color+.swift
  HRHN/Color/CustomColor.swift
  HRHN/Color/UIColor+.swift
  HRHN/Colors.xcassets/gray/gray14.colorset/Contents.json
  HRHN/Colors.xcassets/gray/gray1D.colorset/Contents.json
  HRHN/Colors.xcassets/gray/gray22.colorset/Contents.json
  HRHN/Colors.xcassets/gray/gray59.colorset/Contents.json
  HRHN/Colors.xcassets/gray/grayB9.colorset/Contents.json
  HRHN/Colors.xcassets/gray/grayD0.colorset/Contents.json
  HRHN/Colors.xcassets/gray/grayEF.colorset/Contents.json
  HRHN/View/UI/Cell/ChallengeCell.swift
  HRHN/View/UI/Cell/ChallengeCellView.swift
  HRHN/View/UI/Cell/SettingCell.swift
  HRHN/View/UI/Component/UIFullWidthButton.swift
  HRHN/View/UI/SwiftUIView/ReviewView.swift
  HRHN/View/VC/AddViewController.swift
  HRHN/View/VC/ModifyViewController.swift
  HRHN/View/VC/OnBoarding/OBThirdViewController.swift
  HRHN/View/VC/RecordViewController.swift
  HRHN/View/VC/SettingViewController.swift
  HRHN/View/VC/TodayViewController.swift
Labels: design

#74 [Feat] 지난 챌린지 탭에서 챌린지 평가
  HRHN/View/UI/Cell/ChallengeCell.swift
  HRHN/View/UI/SwiftUIView/ReviewView.swift
  HRHN/View/VC/RecordViewController.swift
  HRHN/View/VC/ReviewViewController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/ReviewViewModel.swift
  HRHN/ViewModel/TodayViewModel.swift
Labels: 기능추가

#79 [Feat] Localization
  HRHN.xcodeproj/project.pbxproj
  HRHN.xcodeproj/xcshareddata/xcschemes/HRHN.xcscheme
  HRHN/Assets.xcassets/onboarding/mock.imageset/mock.png
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/Contents.json
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/en_dark.png
  HRHN/Assets.xcassets/onboarding/onboarding-1.imageset/en_light.png
  HRHN/Extension/Date+.swift
  HRHN/Extension/String+.swift
  HRHN/Helper/I18N.swift
  HRHN/Localization/en.lproj/InfoPlist.strings
  HRHN/Localization/en.lproj/Localizable.strings
  HRHN/Localization/ko.lproj/InfoPlist.strings
  HRHN/Localization/ko.lproj/Localizable.strings
  HRHN/View/UI/Cell/RecordHeaderView.swift
  HRHN/View/UI/SwiftUIView/ReviewView.swift
  HRHN/View/VC/AddViewController.swift
  HRHN/View/VC/ModifyViewController.swift
  HRHN/View/VC/OnBoarding/OBSecondViewController.swift
  HRHN/View/VC/OnBoarding/OBThirdViewController.swift
  HRHN/View/VC/OnBoarding/OnBoardingPageViewController.swift
  HRHN/View/VC/SettingViewController.swift
  HRHN/View/VC/TabBarController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/SettingViewModel.swift
  LockscreenWidget/LockscreenWidget.swift
Labels: Localization

#80 [FIX] 알림 삭제 버그 수정
  HRHN/View/VC/SettingViewController.swift
  HRHN/View/VC/TodayViewController.swift
  HRHN/ViewModel/SettingViewModel.swift
  HRHN/ViewModel/TodayViewModel.swift
Labels: bug

#83 [Hotfix] 텍스트 오류 수정
  HRHN.xcodeproj/project.pbxproj
  HRHN/Localization/en.lproj/Localizable.strings
  HRHN/Localization/ko.lproj/Localizable.strings
Labels: bug
